### ISSUE TITLE
gzip圧縮されたファイルのプロキシに失敗する

### ISSUE THREAD

**Issue by umahaumai** [ToMGitHubN/gcs-basicAuth-cloudRun#3]
ありがとうございます。
Reactで実装されたfrontendのサイト配信で、[Qiita](https://qiita.com/Quantum/items/9ba5b04f05ac0112101f)の記事ベースでGAEで動かしていました。
Node.js v10で古いためリプレースを検討しておりこちらの環境を試させて頂いています。

[gzip 圧縮ファイルのトランス コーディング ](https://cloud.google.com/storage/docs/transcoding?hl=ja) を使ってgz圧縮されたファイルをCloud Storageに配置しているのですが、これらのファイルのプロキシに失敗しています。
非圧縮のファイルであればプロキシできているため環境は正しくできているように思うのですが、なにか解決策はあるでしょうか？

Cloud Runのログ
```
GET 404 914 B 27 ms Chrome 120 https://{CloudRunのURL}/favicon.ico
gcs ReadWithCache: MISS
GET /favicon-32x32.png sent 1046B
...
```

**Comment by umahaumai** [comment]
なお本題とズレるためぶら下げますが、[Google Cloudで WebページをStorageに置いてBasic認証のような簡易認証をつけて表示する](https://zenn.dev/bs_kansai/articles/697fff4625331a) の方法は先に試してみました。
この方法はLBの振り分けルールがCookieの `prefixMatch` で機能するため、GoogleAnalyticsや認証情報をCookieに持つような少しでも複雑なサイトでは使えませんでした。
認証用Cookieが期限切れしたあとに_ga等のcookieを残したままflask_loginへ振り分けられると、二度とCloud Storage側に戻れなくなります。Cookieを削除すれば復帰もできますが、通常運用には少々辛いです。
リファレンスには `regexMatch` もあるようですが、エラーとなり指定できなかったため断念しています。

申し訳ないですgoがよくわからないためissueにさせていただきました。
よろしくお願いいたします。

**Comment by ToMGitHubN** [comment]
記事を見て頂いてありがとうございます。

指摘頂いている、「[gzip 圧縮ファイルのトランス コーディング](https://cloud.google.com/storage/docs/transcoding?hl=ja)」は詳しくありません。
(詳しくないながらですが)gzipファイルされていると404ですので、"Gzipを解除する"対象になっていないのかなと思います。
ファイルはバケットからファイルを取得するシンプルな作りです。

URLに.gz追加するとファイルにはアクセスできるのでしょうか？

**Comment by ToMGitHubN** [comment]
求めている解決方がわかっておらず

ファイルが存在しないときは、"ファイル名" +.gzのファイルを返す
-> 本プログラムの変更で対応できそう

gzファイルを解凍して、ファイルを返却する
-> 申し訳ないですが、別のやりかたを試して頂きたいです。

**Comment by umahaumai** [comment]
返信ありがとうございます。
[gzip 圧縮ファイルのトランス コーディング](https://cloud.google.com/storage/docs/transcoding?hl=ja) は、Cloud Storage で `Content-Encoding: gzip` でgzip圧縮されたファイルを転送する方法になります。

具体的には、Cloud Storageにファイル名はそのまま、バイナリだけgzip圧縮したファイルを配置して、そのうえでメタデータにgzipを設定してファイルを配置します。

<img width="550" alt="スクリーンショット 2023-12-21 19 10 02" src="https://github.com/ToMGitHubN/gcs-basicAuth-cloudRun/assets/58021946/94363a59-24a7-4312-9778-e65afbfb3a5a">

なのでファイル名のURLは.gzを付与しないでアクセスできます。ブラウザが自動で解凍して使ってくれます。

おそらくですが、Cloud Storage への get時にブラウザから投げられたhttpヘッダを全て投げること、
レスポンスもCloud Storage側のレスポンスをすべて返すというのが期待値動作になると思います。
プロキシ経由ですと、Cloud Storageが返すhttpヘッダ(X-Goog-〜) も消えているので、プロキシ動作の過程で省かれているように思います。

**Comment by umahaumai** [comment]
たぶん回答が悪かったので少し追記します。

> ファイルが存在しないときは、"ファイル名" +.gzのファイルを返す
> gzファイルを解凍して、ファイルを返却する

期待しているのは、一般的なApacheやNginxがやるような「Cloud Storageのレスポンスをそのまま返却するようしてほしい」です。
個別の特殊な機能を追加してほしいという話ではありません。

[gzip 圧縮ファイルのトランス コーディング](https://cloud.google.com/storage/docs/transcoding?hl=ja) を使用した状態のファイルに対して、
Cloud Storage へ直接アクセスしてのブラウジングは成功して、
[Qiita](https://qiita.com/Quantum/items/9ba5b04f05ac0112101f) のGAEでも成功していたものが、
本プログラムを経由すると失敗するという状況を修正いただきたいのです。

可能性としてこの辺怪しいと思っています。

- ライブラリを使ってGoogle Storageに接続した結果、本プログラムで取得したバイナリが既にgzip圧縮解除された状態で、非圧縮のバイナリを返却しているにも関わらず httpヘッダに `Content-Encoding: gzip` が付与されているとか Content-Length が解凍後のサイズになっていない
- gzip圧縮されたまま返却しているが、`Content-Encoding: gzip` などhttpヘッダが欠如している

**Comment by ToMGitHubN** [comment]
回答ありがとうございます。
「[gzip 圧縮ファイルのトランス コーディング](https://cloud.google.com/storage/docs/transcoding?hl=ja)」について理解進みました。

可能性として挙げて頂いた、"圧縮解除したがヘッダーが不適切"と"圧縮状態で送信しておりgzipヘッダーがない”について検証しました。

結論を先に書くと、「トランス コーディング」は実行されて非圧縮で取得しているがヘッダーが適切でないことで問題が起こっていそうです。

ヘッダーは、cloud storageのデータを参考にしているため
* `Content-Encoding: gzip` が付与されている
*  `Content-Length` が格納時のサイズで送信値と違う

対応として、
* `Content-Encoding: gzip` の際は`Content-Encoding` を返さない
*  `Content-Length`は送信データから取得

としました。

[fixブランチ](https://github.com/ToMGitHubN/gcs-basicAuth-cloudRun/tree/fix-gzip)を作りました。
試して頂けないでしょうか。

---

検証の流れを記載します。

gsutilコマンドでgzip圧縮したファイルをcloud storageにアップロードしました。

```
gsutil cp -z html ./index.html gs://hoge-bucket
```
これで、以下のようにgzipのメタデータがついてアップされて、ファイルサイズも縮小しています。
<img width="404" alt="image" src="https://github.com/ToMGitHubN/gcs-basicAuth-cloudRun/assets/17189935/64254018-18d6-4b91-af5c-65f5721954f6">

それをChromeのデベロッパーツールで確認すると、まずgzipのメタデータが入っていることは確認できました。
ただし、ページは表示できませんでした。

<img width="268" alt="image" src="https://github.com/ToMGitHubN/gcs-basicAuth-cloudRun/assets/17189935/a29299c9-b7f9-4597-9f25-6592308fc6b4">

次に、ソースを変更してメタデータを送信しないようにするとブラウザでページを表示することができました。
それを踏まえて上の対応を行いました。

**Comment by umahaumai** [comment]
@ToMGitHubN 
素早いご対応ありがとうございました！
[gzip 圧縮ファイルのトランス コーディング](https://cloud.google.com/storage/docs/transcoding?hl=ja) を設置したCloud Storage へのプロキシにおいても、ブラウザで正常動作したのを確認しました。
スマホからも確認してみましたが、[Qiita](https://qiita.com/Quantum/items/9ba5b04f05ac0112101f) 版と比較してもわからない程度には十分早く、実用範囲内かと思います。
運用で利用させていただきたいと思います。ありがとうございます。

**Comment by umahaumai** [comment]
一点、

> Content-Encoding: gzip が付与されている
> Content-Length が格納時のサイズで送信値と違う

ちょっと解釈が違うよう感じました。
`Content-Encoding: gzip` は、対応しているなら転送量を削減するための指定ですので、
本プロキシのCloud Runに届くまではgzip圧縮された状態なんです。
なのでライブラリの中の人がhttpヘッダを勝手に解釈してungzipしているはずですね。
GAEの

**Comment by umahaumai** [comment]
一点、

> Content-Encoding: gzip が付与されている
> Content-Length が格納時のサイズで送信値と違う

ちょっと解釈が違うように感じました。
`Content-Encoding: gzip` は転送量を削減するための指定で、送信されるバイナリそのものはgzip圧縮された状態なんです。
なので Cloud Run で動作する本プログラム に届いた時点ではgzip圧縮された状態で、Content-Lengthと相違ないはずなんです。
利用しているライブラリの中の人がhttpヘッダを自動で解釈してungzip したことで、今回の問題に陥ったものと思います。

もしCloud Storageを扱うライブラリの設定でunzipしない指定があれば、それをしておくのが恐らくは正解で、
それが大変であれば fix-gzip ブランチの Content-Length の上書きということかと思いました。

社内の確認用の用途としては不要な最適化かと思いますので、もし手軽に変更できそうでしたらお試しいただけますと。

**Comment by ToMGitHubN** [comment]
ご確認ありがとうございます。

gzip圧縮で転送した際のContent-Lengthですが、軽く調べたところ展開後のサイズをContent-Lengthにいれないといけないようです。

実際に展開してサイズがわかっている現状はベター思っています。

* 問題は解決していること
* 別の方が作ったProxyを使っているので変更しすぎると重要な変更が出ると取り込めないこと
を考えてこれでFixとしたいと思います。
